"""empty message

Revision ID: 97e15ffcf711
Revises: 733c7f0cde12
Create Date: 2020-10-03 03:24:07.812151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e15ffcf711'
down_revision = '733c7f0cde12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    # ### end Alembic commands ###
